[pytest]
# 指定测试文件所在的目录
testpaths = tests
# 指定测试文件的命名规则
python_files = test_*.py
# 指定测试类的命名规则
python_classes = Test*
# 指定测试函数的命名规则
python_functions = test_*
# 添加默认的命令行参数，例如 -v 表示详细输出，-s 表示允许print语句输出
addopts = -v -s